server:
  port: 8081
database:
  type: sqlite3
  url: "test.db"
  prot: 3396
  username: "root"
  pasword: "password"

security:
  token:
    auth: "doter1995"
    slate: "test"
email:
  host: "smtp.qq.com"
  smtp: "smtp.qq.com:25"
  account: "doter1995@qq.com"
  password: ""
redis:
  url: ""
  db: 0
  password: ""
